### ISSUE TITLE
Migrate files to Honeycomb, archive repository

### ISSUE THREAD

**Issue by RobertGemmaJr** [brown-ccv/behavioral-task-trials#53]
These example tasks can be brought directly into [Honeycomb](https://github.com/brown-ccv/honeycomb) as example trials. From there this repository can be archived

- [ ] Migrate files to Honeycomb
- [ ] Add example trials to Beehive

**Comment by RobertGemmaJr** [comment]
Going to keep a running list of trials that have been moved here:

- `slider` has been moved to `trials/Slider`
- 

## TODO

### Trials

- [ ] survey
- [ ] countdown
- [ ] fixation
- [ ] multiSurvey
- [ ] showImage
- [ ] showMessage
- [ ] slider
- [ ] survey
- [ ] userID

### Utils

- [ ] jitterx (was already in Honeycomb)
- [ ] init (From App.js)

### Markup

- [ ] photodiode
- [ ] stimuli
